# Generated by Django 4.1.5 on 2023-01-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panneau',
            name='contrat_panneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.contrat'),
        ),
    ]
